import { ThemeConfig } from '../types/theme';

export const themes: ThemeConfig[] = [
  {
    name: 'space',
    label: '🌌 Space',
    background: 'bg-[url("/images/space.webp")] bg-cover bg-fixed bg-center bg-no-repeat before:absolute before:inset-0 before:bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] before:from-purple-900/80 before:via-slate-900/90 before:to-black/95 before:-z-10',
    boardBg: 'bg-slate-800/50 backdrop-blur-sm',
    xSymbol: '🚀',
    oSymbol: '🪐',
    winningBg: 'bg-purple-500/30',
    buttonBg: 'bg-slate-800/50',
    buttonHoverBg: 'hover:bg-slate-700/50',
    selectedButtonBg: 'bg-purple-600',
  },
  {
    name: 'sunset',
    label: '🌅 Sunset',
    background: 'bg-[url("/images/sunset.webp")] bg-cover bg-fixed bg-center bg-no-repeat before:absolute before:inset-0 before:bg-gradient-to-b before:from-orange-500/70 before:via-pink-500/80 before:to-purple-900/90 before:-z-10',
    boardBg: 'bg-orange-900/30 backdrop-blur-sm',
    xSymbol: '☀️',
    oSymbol: '🌅',
    winningBg: 'bg-orange-400/30',
    buttonBg: 'bg-orange-900/30',
    buttonHoverBg: 'hover:bg-orange-800/30',
    selectedButtonBg: 'bg-orange-600',
  },
  {
    name: 'ocean',
    label: '🌊 Ocean',
    background: 'bg-[url("/images/ocean.webp")] bg-cover bg-fixed bg-center bg-no-repeat before:absolute before:inset-0 before:bg-gradient-to-b before:from-blue-400/70 before:via-blue-600/80 before:to-blue-900/90 before:-z-10',
    boardBg: 'bg-blue-900/30 backdrop-blur-sm',
    xSymbol: '🐋',
    oSymbol: '🐠',
    winningBg: 'bg-blue-400/30',
    buttonBg: 'bg-blue-900/30',
    buttonHoverBg: 'hover:bg-blue-800/30',
    selectedButtonBg: 'bg-blue-600',
  },
  {
    name: 'forest',
    label: '🌲 Forest',
    background: 'bg-[url("/images/forest.webp")] bg-cover bg-fixed bg-center bg-no-repeat before:absolute before:inset-0 before:bg-gradient-to-b before:from-green-400/70 before:via-green-600/80 before:to-green-900/90 before:-z-10',
    boardBg: 'bg-green-900/30 backdrop-blur-sm',
    xSymbol: '🌲',
    oSymbol: '🍃',
    winningBg: 'bg-green-400/30',
    buttonBg: 'bg-green-900/30',
    buttonHoverBg: 'hover:bg-green-800/30',
    selectedButtonBg: 'bg-green-600',
  },
  {
    name: 'mountain',
    label: '⛰️ Mountain',
    background: 'bg-[url("/images/mountain.webp")] bg-cover bg-fixed bg-center bg-no-repeat before:absolute before:inset-0 before:bg-gradient-to-b before:from-slate-300/70 before:via-slate-400/80 before:to-slate-900/90 before:-z-10',
    boardBg: 'bg-slate-900/30 backdrop-blur-sm',
    xSymbol: '⛰️',
    oSymbol: '🗻',
    winningBg: 'bg-slate-400/30',
    buttonBg: 'bg-slate-900/30',
    buttonHoverBg: 'hover:bg-slate-800/30',
    selectedButtonBg: 'bg-slate-600',
  },
  {
    name: 'classic',
    label: '🎮 Classic',
    background: 'bg-[url("/images/classic.webp")] bg-cover bg-fixed bg-center bg-no-repeat before:absolute before:inset-0 before:bg-gradient-to-b before:from-blue-100/95 before:to-white/98 before:-z-10',
    boardBg: 'bg-white/80 backdrop-blur-sm',
    xSymbol: '❌',
    oSymbol: '⭕',
    winningBg: 'bg-green-200',
    buttonBg: 'bg-slate-700/80',
    buttonHoverBg: 'hover:bg-slate-600/80',
    selectedButtonBg: 'bg-blue-600',
  },
];